=== DrMiaow/metawrapLegacy/javascript/tests/wirewrap/wirewrap.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    $Id: wirewrap.xsd,v 1.4 2007/11/07 02:03:50 james Exp $

    $Log: wirewrap.xsd,v $
    Revision 1.4  2007/11/07 02:03:50  james
    Support for new wirewrap operations

    Revision 1.3  2005/11/02 20:55:58  james
    Changed wirewrap to allow window event handlers to be added

    Revision 1.2  2005/08/29 07:51:41  james
    Latest wirewrap test

    Revision 1.1  2005/08/25 12:23:15  james
    Moved code

    Revision 1.3  2005/07/02 13:23:10  james
    Getting schema definition w3 compliant

    
    @brief Schema definition for the MetaWrap WireWrap XML Schema
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xsd.metawrap.com/wirewrap/1.0/"
	xmlns:wr="http://xsd.metawrap.com/wirewrap/1.0/" elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation xml:lang="en">
            Schema definition for MetaWrap WireWrap
            Copyright 2005 The MetaWrap Projet
        </xs:documentation>
	</xs:annotation>
	<xs:element name="wirewrap">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="onload" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="onunload" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							
				<xs:element name="selector" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="destructor" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onabort" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onblur" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onchange" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onclick" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="ondblClick" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onerror" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onfocus" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onkeydown" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onkeypress" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onkeyup" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onload" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onmousedown" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onmouseout" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onmouseover" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onmouseup" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onreset" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onresize" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="onsubmit" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="onunload" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="style" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="before" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="after" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="add" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="replace" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="remove" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="swap" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
							<xs:element name="prefix" type="xs:string" minOccurs="0" maxOccurs="unbounded" />																					
							<xs:element name="suffix" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DrMiaow/metawrapLegacy/javascript/tests/wirewrap/test_5_wirewrap_base.xml
<?xml version="1.0" ?>
<!--
    $Id: test_5_wirewrap_base.xml,v 1.1 2005/11/01 11:58:00 james Exp $

    $Log: test_5_wirewrap_base.xml,v $
    Revision 1.1  2005/11/01 11:58:00  james
    Some renaming to make more sense, getting ready for
    second stage of pipeline

    Revision 1.1  2005/10/05 12:45:33  james
    Got nested style XML working

    Revision 1.2  2005/10/04 13:43:46  james
    Got some more testcases working for wirewrap

    Revision 1.3  2005/08/31 12:41:53  james
    Testcase 3 now processes style and behavior xml
    on browsers that have XSLT support.

    Revision 1.2  2005/08/31 10:23:19  james
    Adding xsd directort for schema definitions

    Revision 1.1  2005/08/29 08:04:10  james
    Latest wirewrap test

    Revision 1.1  2005/08/25 12:23:15  james
    Moved code

    Revision 1.4  2005/07/03 03:24:52  james
    Fixed issue in XSLT and in example XML

    Revision 1.3  2005/07/02 13:23:10  james
    Getting schema definition w3 compliant

    
    @brief Example XML for css selector applied HTML/JavaScript behaviors
 -->
<wirewrap xmlns="http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xsd.metawrap.com/wirewrap/1.0/ http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd" >
   <selector css="#example li">
      <onclick>this.parentNode.removeChild(this); return false;</onclick>
   </selector>

   <selector css="#fading-list li">
      <onclick>new Effect2.Fade(this); return false;</onclick>
   </selector>

   <selector css="ul#sortable-list">
      <constructor>Sortable.create(p_e);</constructor>
   </selector>

   <selector css="#shaky li">
      <onclick>new Effect2.Shake(this);</onclick>
   </selector>

   <selector css=".dropout li">
      <onclick>new Effect2.DropOut(this);</onclick>

      <onmouseover>this.className = "hover";</onmouseover>

      <onmouseout>this.className = "";</onmouseout>
   </selector>
   
    <selector css=".wrap">        
        <style>
            width: 67%;
            margin: 0 0 1em 14%;
            padding: 2% 3% 2% 5%;
            BACKGROUND: white;
            border-style: solid;
            border-width: 1px;
            top: -1px;                
        </style>              
    </selector>

    <selector css="h1,h2,h3,h4">        
        <style>
            position: relative;
            left: -1em;
            clear: both;
        </style>              
    </selector>

    <selector css="body">        
        <style>
        margin: 0;
        padding: 0;
        background: #FC0;
        font: 0.8em trebuchet ms;
        </style>              
    </selector>

    <selector css="em">        
        <style>
            background: #ffc;
        </style>              
    </selector>

    <selector css="pre">        
        <style>        
            font-size: 1.1em;
            background: #f0f0f0;
            -moz-border-radius: 10px;
            padding: 1em;
        </style>              
    </selector>


    <selector css="pre span">        
        <style>       
            font-weight: bold;
        </style>              
    </selector>

    <selector css=".selector, pre b">        
        <style>       
            color: red;
        </style>              
    </selector>


    <selector css=".beh">        
        <style>
            color: blue;
        </style>              
    </selector>

    <selector css=".event">        
        <style>
            color: green;
        </style>              
    </selector>

    <selector css="#sortable-list li">        
        <style>
            cursor:move;
            -moz-user-select: none;
            width: 100%;
        </style>              
    </selector>

    <selector css=".dropout li">        
        <style>
            width: 100px;
            line-height: 100px;
            text-align: center;
            float: left;
            margin: 5px;
            border: 1px solid #ccc;
            list-style: none;
        </style>              
    </selector>


    <selector css=".dropout li.hover">        
        <style>
            background: yellow;
        </style>              
    </selector>   
   
</wirewrap>

=== DrMiaow/metawrapLegacy/javascript/tests/wirewrap/test_4_wirewrap_remix.xml
<?xml version="1.0" ?>
<!--
    $Id: test_4_wirewrap_remix.xml,v 1.6 2007/11/07 02:03:50 james Exp $

    $Log: test_4_wirewrap_remix.xml,v $
    Revision 1.6  2007/11/07 02:03:50  james
    Support for new wirewrap operations

    Revision 1.5  2007/10/24 10:35:00  james
    *** empty log message ***

    Revision 1.4  2007/10/24 09:44:12  james
    Working out the semantics of the new skin system

    Revision 1.3  2005/11/09 13:06:36  james
    added stub for smsmodem

    Revision 1.2  2005/11/02 20:55:58  james
    Changed wirewrap to allow window event handlers to be added

    Revision 1.1  2005/11/02 11:41:22  james
    Got basic remix transform happening
    
    @brief Example XML for css selector applied HTML/JavaScript behaviors
 -->
<wirewrap xmlns="http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xsd.metawrap.com/wirewrap/1.0/ http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd" >
    <onload>
        alert("Loaded");
    </onload>          
    
    <selector css="*">        
        <style>
            font-family: "Gothic" fantasy;
        </style>              
    </selector>
       
    <selector css="#sortable-list">        
        <remove/>
    </selector>

    <selector css="#sortable-list-heading">
    
        <before><![CDATA[        
            <h2 class="test">before</h2>           
        ]]></before>
    
        <after><![CDATA[        
            <h2 class="test">after</h2>           
        ]]></after>
        
        <add><![CDATA[        
            I am the walrus!
        ]]></add>

        <add><![CDATA[        
            <b>Release the hounds!!</b>
        ]]></add>
        
        <replace><![CDATA[        
            I am replacement content!
        ]]></replace>        
        
        <prefix><![CDATA[        
            <i>*NEW*</i>
        ]]></prefix>        
        
        
        <add><component type="xyz" name="123"></component></add>
        
        <swap css="#fading-list-heading" />
        

    </selector>
    
    <selector css="h2">
        <prefix><![CDATA[        
            Depressing
        ]]></prefix>         
    </selector>      

    <selector css="#sortable-list">
        <replace><![CDATA[        
            <h1 class="test">Replaced!</h1>           
        ]]></replace>
    </selector>    
           
    <selector css="body">
        <style>
            background: black;
        </style>
        <onclick>
            alert("Hello Cruel World");
        </onclick>        
    </selector>   
    
    <selector css=".dropout li.hover">        
        <style>
            background: green;
        </style>              
    </selector>   
    
</wirewrap>

=== DrMiaow/metawrapLegacy/javascript/tests/wirewrap/test_3_wirewrap_remix.xml
<?xml version="1.0" ?>
<!--
    $Id: test_3_wirewrap_remix.xml,v 1.1 2007/08/14 07:56:34 james Exp $

    $Log: test_3_wirewrap_remix.xml,v $
    Revision 1.1  2007/08/14 07:56:34  james
    *** empty log message ***

    Revision 1.3  2005/11/09 13:06:36  james
    added stub for smsmodem

    Revision 1.2  2005/11/02 20:55:58  james
    Changed wirewrap to allow window event handlers to be added

    Revision 1.1  2005/11/02 11:41:22  james
    Got basic remix transform happening
    
    @brief Example XML for css selector applied HTML/JavaScript behaviors
 -->
<wirewrap xmlns="http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xsd.metawrap.com/wirewrap/1.0/ http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd" >
    <onload>
        alert("Loaded");
    </onload>          
    
    <selector css="*">        
        <style>
            font-family: "Gothic" fantasy;
        </style>              
    </selector>
       
    <selector css="#sortable-list li">        
        <cut/>
        
        <replace>
        </replace>
        
        <prefix>
			Depressed
        </prefix>        
    </selector>
           
    <selector css="body">
        <style>
            background: black;
        </style>
        <onclick>
            alert("Hello Cruel World");
        </onclick>        
    </selector>   
    
    <selector css=".dropout li.hover">        
        <style>
            background: green;
        </style>              
    </selector>   
    
</wirewrap>

=== DrMiaow/metawrapLegacy/javascript/tests/wirewrap/test_8_wirewrap_base.xml
<?xml version="1.0" ?>
<!--
    $Id: test_8_wirewrap_base.xml,v 1.3 2007/08/13 09:53:41 james Exp $

    $Log: test_8_wirewrap_base.xml,v $
    Revision 1.3  2007/08/13 09:53:41  james
    New behaviors

    Revision 1.2  2007/08/10 08:24:21  james
    Added bahavior lib

    Revision 1.1  2007/08/07 10:23:50  james
    WireWrap prototype example working with Adobe Fireworks CS3
    
    @brief Example XML for css selector applied HTML/JavaScript behaviors
 -->
<wirewrap xmlns="http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xsd.metawrap.com/wirewrap/1.0/ http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd" >
   <selector css="#watch">
      <constructor>
        MetaWrap.Behavior.Navigation.g_focus = p_e.id;      
        MetaWrap.Behavior.Navigation.addNav(p_e,"read","listen","watch.htm","watch.htm","watch.htm");
      </constructor>       
   
      <onclick>new Effect2.DropOut(this);</onclick>
   </selector>

   <selector css="#listen">   
      <constructor>MetaWrap.Behavior.Navigation.addNav(p_e,"watch","play",null,null,"listen.htm");</constructor>             
    </selector>

   <selector css="#play">   
      <constructor>MetaWrap.Behavior.Navigation.addNav(p_e,"listen","read",null,null,"play.htm");</constructor>             
    </selector>

   <selector css="#read">   
      <constructor>MetaWrap.Behavior.Navigation.addNav(p_e,"play","watch",null,null,"read.htm");</constructor>             
    </selector>
   
</wirewrap>

=== DrMiaow/metawrapLegacy/javascript/tests/wirewrap/behavior.xml
<?xml version="1.0" ?>
<!--
    $Id: behavior.xml,v 1.3 2005/10/04 13:43:45 james Exp $

    $Log: behavior.xml,v $
    Revision 1.3  2005/10/04 13:43:45  james
    Got some more testcases working for wirewrap

    Revision 1.2  2005/08/31 12:41:53  james
    Testcase 3 now processes style and behavior xml
    on browsers that have XSLT support.

    Revision 1.1  2005/08/25 12:23:15  james
    Moved code

    Revision 1.4  2005/07/03 03:24:52  james
    Fixed issue in XSLT and in example XML

    Revision 1.3  2005/07/02 13:23:10  james
    Getting schema definition w3 compliant

    
    @brief Example XML for css selector applied HTML/JavaScript behaviors
 -->
<wirewrap xmlns="http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xsd.metawrap.com/wirewrap/1.0/ http://xsd.metawrap.com/wirewrap/1.0/wirewrap.xsd">
    <selector css="#example li">        
        <onclick>
            this.parentNode.removeChild(this);
        </onclick>              
    </selector>

    <selector css="#fading-list li">
        <onclick>
            new Effect2.Fade(this);
        </onclick>              
    </selector>

    <selector css="ul#sortable-list">    
        <constructor>
            Sortable.create(p_e);
        </constructor>              
    </selector>

    <selector css="#shaky li">        
        <onclick>
            new Effect2.Shake(this)
        </onclick>              
    </selector>

    <selector css=".dropout li">        
        <onclick> 
            new Effect2.DropOut(this)           
        </onclick>
        <onmouseover>
            this.className = "hover";
        </onmouseover>              
        <onmouseout>            
            this.className = "";
        </onmouseout>                      
    </selector>       
</wirewrap>
